#!/bin/bash
# Seed Stripe with all subscription plans using Stripe CLI
# This creates products and prices for: Plus ($20), Pro ($50), Max ($200)

set -euo pipefail

if ! command -v stripe &> /dev/null; then
  echo "Error: Stripe CLI not found. Install it from https://stripe.com/docs/stripe-cli"
  exit 1
fi

if ! command -v jq &> /dev/null; then
  echo "Error: jq not found. Install it with: brew install jq"
  exit 1
fi

echo "Creating Stripe products and prices..."
echo ""

# Plus Plan - $20/month
echo "Creating Plus Plan..."
PLUS_OUTPUT=$(stripe products create --name "Plus Plan" --description "\$20 worth of credits/month, Share apps via App Clips, Vibecode Sandbox, Sandbox projects, App Store submission" 2>&1) || { echo "✗ Stripe command failed"; echo "$PLUS_OUTPUT"; exit 1; }
if echo "$PLUS_OUTPUT" | jq -e '.id' > /dev/null 2>&1; then
  PLUS_PRODUCT=$(echo "$PLUS_OUTPUT" | jq -r '.id')
  echo "  Created product: $PLUS_PRODUCT"
  PLUS_PRICE_OUTPUT=$(stripe prices create --product "$PLUS_PRODUCT" --unit-amount 2000 --currency usd --recurring.interval month 2>&1) || { echo "✗ Stripe price command failed"; echo "$PLUS_PRICE_OUTPUT"; exit 1; }
  if echo "$PLUS_PRICE_OUTPUT" | jq -e '.id' > /dev/null 2>&1; then
    PLUS_PRICE=$(echo "$PLUS_PRICE_OUTPUT" | jq -r '.id')
    echo "✓ Plus: Product $PLUS_PRODUCT, Price $PLUS_PRICE"
  else
    echo "✗ Failed to create Plus price"
    echo "$PLUS_PRICE_OUTPUT" | head -5
    exit 1
  fi
else
  echo "✗ Failed to create Plus product"
  echo "$PLUS_OUTPUT" | head -5
  exit 1
fi

# Pro Plan - $50/month
echo "Creating Pro Plan..."
PRO_OUTPUT=$(stripe products create --name "Pro Plan" --description "\$55 worth of credits/month, Share apps via App Clips, Vibecode Sandbox, SSH to Cursor, Sandbox projects, App Store submission, Download source code" 2>&1) || { echo "✗ Stripe command failed"; echo "$PRO_OUTPUT"; exit 1; }
if echo "$PRO_OUTPUT" | jq -e '.id' > /dev/null 2>&1; then
  PRO_PRODUCT=$(echo "$PRO_OUTPUT" | jq -r '.id')
  echo "  Created product: $PRO_PRODUCT"
  PRO_PRICE_OUTPUT=$(stripe prices create --product "$PRO_PRODUCT" --unit-amount 5000 --currency usd --recurring.interval month 2>&1) || { echo "✗ Stripe price command failed"; echo "$PRO_PRICE_OUTPUT"; exit 1; }
  if echo "$PRO_PRICE_OUTPUT" | jq -e '.id' > /dev/null 2>&1; then
    PRO_PRICE=$(echo "$PRO_PRICE_OUTPUT" | jq -r '.id')
    echo "✓ Pro: Product $PRO_PRODUCT, Price $PRO_PRICE"
  else
    echo "✗ Failed to create Pro price"
    echo "$PRO_PRICE_OUTPUT" | head -5
    exit 1
  fi
else
  echo "✗ Failed to create Pro product"
  echo "$PRO_OUTPUT" | head -5
  exit 1
fi

# Max Plan - $200/month
echo "Creating Max Plan..."
MAX_OUTPUT=$(stripe products create --name "Max Plan" --description "\$220 worth of credits/month, All Pro features, 24/7 Priority support, 10% bonus on credit purchases" 2>&1) || { echo "✗ Stripe command failed"; echo "$MAX_OUTPUT"; exit 1; }
if echo "$MAX_OUTPUT" | jq -e '.id' > /dev/null 2>&1; then
  MAX_PRODUCT=$(echo "$MAX_OUTPUT" | jq -r '.id')
  echo "  Created product: $MAX_PRODUCT"
  MAX_PRICE_OUTPUT=$(stripe prices create --product "$MAX_PRODUCT" --unit-amount 20000 --currency usd --recurring.interval month 2>&1) || { echo "✗ Stripe price command failed"; echo "$MAX_PRICE_OUTPUT"; exit 1; }
  if echo "$MAX_PRICE_OUTPUT" | jq -e '.id' > /dev/null 2>&1; then
    MAX_PRICE=$(echo "$MAX_PRICE_OUTPUT" | jq -r '.id')
    echo "✓ Max: Product $MAX_PRODUCT, Price $MAX_PRICE"
  else
    echo "✗ Failed to create Max price"
    echo "$MAX_PRICE_OUTPUT" | head -5
    exit 1
  fi
else
  echo "✗ Failed to create Max product"
  echo "$MAX_OUTPUT" | head -5
  exit 1
fi

echo ""
echo "=========================================="
echo "Stripe products and prices created!"
echo "=========================================="
echo ""

# Write to .env file if it exists, otherwise just output
ENV_FILE=".env"
if [ -f "$ENV_FILE" ]; then
  echo "Updating $ENV_FILE with price IDs..."
  # Remove old price IDs if they exist
  sed -i.bak '/^STRIPE_PRICE_/d' "$ENV_FILE"
  # Add new ones
  echo "" >> "$ENV_FILE"
  echo "# Stripe Price IDs (auto-generated by seed-stripe.sh)" >> "$ENV_FILE"
  echo "STRIPE_PRICE_PLUS=$PLUS_PRICE" >> "$ENV_FILE"
  echo "STRIPE_PRICE_PRO=$PRO_PRICE" >> "$ENV_FILE"
  echo "STRIPE_PRICE_MAX=$MAX_PRICE" >> "$ENV_FILE"
  echo "✓ Updated $ENV_FILE"
  echo ""
fi

echo "Export these environment variables:"
echo ""
echo "export STRIPE_PRICE_PLUS=$PLUS_PRICE"
echo "export STRIPE_PRICE_PRO=$PRO_PRICE"
echo "export STRIPE_PRICE_MAX=$MAX_PRICE"
echo ""
echo "Then restart Supabase: supabase stop && supabase start"
echo ""











