version: '3'

tasks:
  default:
    desc: show available tasks
    cmds:
      - task --list

  start:
    desc: start the API local server
    cmds:
      - supabase start

  serve:
    desc: serve the API functions locally
    cmds:
      - supabase functions serve api --no-verify-jwt

  dev:local:
    desc: start local Supabase and serve the API functions
    cmds:
      - supabase start
      - supabase functions serve api --no-verify-jwt

  deploy:
    desc: deploy API to production (Supabase)
    cmds:
      - supabase secrets set --env-file .env.prod
      - task: supabase:deploy

  ###

  supabase:link:
    desc: link local Supabase project to hosted project
    cmds:
      - supabase link --project-ref {{.SUPABASE_PROJECT_REF}}

  supabase:db:push:
    desc: push database migrations to linked Supabase project
    cmds:
      - supabase db push

  supabase:functions:deploy:
    desc: deploy edge functions to linked Supabase project
    cmds:
      - supabase functions deploy api

  supabase:deploy:
    desc: deploy Supabase backend (migrations + functions)
    cmds:
      - task: supabase:db:push
      - task: supabase:functions:deploy

  supabase:init:
    desc: initialize Supabase project (run once)
    cmds:
      - supabase init

  supabase:start:
    desc: start local Supabase emulator
    cmds:
      - supabase start

  supabase:stop:
    desc: stop local Supabase emulator
    cmds:
      - supabase stop

  supabase:status:
    desc: show Supabase emulator status and connection info
    cmds:
      - supabase status

  supabase:reset:
    desc: reset Supabase database and apply schema (local)
    cmds:
      - supabase db reset

  supabase:reset-remote:
    desc: 'reset remote Supabase database (WARNING: deletes all data)'
    cmds:
      - supabase db reset --linked

  supabase:studio:
    desc: open Supabase Studio UI in browser
    cmds:
      - supabase studio

  ###
  # Tests
  ###

  test:
    desc: run all tests (unit + integration)
    cmds:
      - pytest test/ -v --ignore=test/e2e --ignore=test/cloud

  test:integration:
    desc: run integration tests (requires local Supabase)
    cmds:
      - pytest test/integration/ -v -m integration

  test:e2e:local:
    desc: run e2e tests against local environment
    cmds:
      - |
        echo "Running e2e tests against local environment..."
        echo "Prerequisites: supabase running (task start), VMs registered"
        pytest test/e2e/ -v -m e2e -s

  test:e2e:prod:
    desc: run e2e tests against production
    cmds:
      - |
        echo "Running e2e tests against production..."
        EB_API_ENV_FILE=.env.prod pytest test/e2e/ -v -m e2e -s
