version: '3'

tasks:
  default:
    desc: show available tasks
    cmds:
      - task --list

  dev:local:
    desc: start local Supabase and serve the API functions
    cmds:
      - supabase stop && supabase start
      - supabase functions serve api --no-verify-jwt

  deploy:
    desc: deploy API to production (Supabase)
    cmds:
      - |
        set -euo pipefail
        echo "=== checking for unstaged changes ==="
        if ! git diff --quiet || ! git diff --cached --quiet; then
          echo "error: unstaged or uncommitted changes detected" >&2
          echo "please commit or stash your changes before deploying" >&2
          git status --short
          exit 1
        fi
        echo "✓ no unstaged changes"
      - |
        set -euo pipefail
        echo "=== checking for unpushed commits ==="
        UPSTREAM="$(git rev-parse --abbrev-ref @{u} 2>/dev/null || true)"
        if [ -z "${UPSTREAM}" ]; then
          echo "error: current branch has no upstream. Push and set upstream before deploying." >&2
          exit 1
        fi
        if git rev-list @{u}..HEAD 2>/dev/null | grep -q .; then
          echo "error: you have commits that are not pushed to ${UPSTREAM}" >&2
          echo "please push your changes before deploying" >&2
          git log @{u}..HEAD --oneline
          exit 1
        fi
        echo "✓ all commits pushed"
      - |
        echo ""
        echo "=== Pre-deploy checklist ==="
        echo ""
        read -p "Have you run e2e tests? (task test:e2e:prod) [y/N]: " confirm
        if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
          echo ""
          echo "Please run e2e tests first:"
          echo "  task test:e2e:prod"
          echo ""
          echo "Or bypass with: task deploy:force"
          exit 1
        fi
      - supabase secrets set --env-file .env.prod
      - task: _supabase:deploy

  deploy:force:
    desc: deploy API without e2e confirmation (use with caution)
    cmds:
      - |
        set -euo pipefail
        echo "=== checking for unstaged changes ==="
        if ! git diff --quiet || ! git diff --cached --quiet; then
          echo "error: unstaged or uncommitted changes detected" >&2
          echo "please commit or stash your changes before deploying" >&2
          git status --short
          exit 1
        fi
        echo "✓ no unstaged changes"
      - |
        set -euo pipefail
        echo "=== checking for unpushed commits ==="
        UPSTREAM="$(git rev-parse --abbrev-ref @{u} 2>/dev/null || true)"
        if [ -z "${UPSTREAM}" ]; then
          echo "error: current branch has no upstream. Push and set upstream before deploying." >&2
          exit 1
        fi
        if git rev-list @{u}..HEAD 2>/dev/null | grep -q .; then
          echo "error: you have commits that are not pushed to ${UPSTREAM}" >&2
          echo "please push your changes before deploying" >&2
          git log @{u}..HEAD --oneline
          exit 1
        fi
        echo "✓ all commits pushed"
      - supabase secrets set --env-file .env.prod
      - task: _supabase:deploy

  ###
  # Tests
  ###

  test:unit:
    desc: run unit tests only (no services needed)
    cmds:
      - pytest test/unit/ -v || [ $? -eq 5 ]  # exit 5 = no tests collected, OK

  test:local:
    desc: run local tests (requires task dev:local)
    cmds:
      - |
        echo "Running local tests..."
        echo "Prerequisites: task dev:local running in another terminal"
        pytest test/local/ -v -m local --env local

  test:local:auto:
    desc: run local tests (auto-starts services)
    cmds:
      - |
        set -e
        echo "=== Starting Supabase ==="
        supabase start || true

        echo "=== Starting functions server in background ==="
        supabase functions serve api --no-verify-jwt &
        SERVE_PID=$!
        sleep 3

        echo "=== Running local tests ==="
        pytest test/local/ -v -m local --env local || TEST_EXIT=$?

        echo "=== Stopping functions server ==="
        kill $SERVE_PID 2>/dev/null || true

        exit ${TEST_EXIT:-0}

  test:multi:
    desc: run multi-repo tests (requires worker + userland running)
    cmds:
      - |
        echo "Running multi-repo tests..."
        echo "Prerequisites: eb-api, eb-worker, eb-userland all running"
        pytest test/multi/ -v -m multi --env local

  test:cloud:
    desc: run cloud tests (requires GCP access)
    cmds:
      - pytest test/cloud/ -v -m cloud --env prod

  test:e2e:local:
    desc: run e2e tests against local environment
    cmds:
      - |
        echo "Running e2e tests against local environment..."
        echo "Prerequisites: supabase running (task dev:local), VMs registered"
        pytest test/e2e/ -v -m e2e -s --env local

  test:e2e:prod:
    desc: run e2e tests against production
    cmds:
      - |
        echo "Running e2e tests against production..."
        pytest test/e2e/ -v -m e2e -s --env prod

  test:lint:
    desc: run linting (deno for functions, ruff for Python tests)
    cmds:
      - deno lint supabase/functions/
      - ruff check .

  ###
  # Setup
  ###

  hooks:install:
    desc: install git pre-commit hooks
    cmds:
      - ./scripts/install-hooks.sh

  ###
  # Internal Tasks
  ###

  _supabase:link:
    desc: link local Supabase project to hosted project
    cmds:
      - supabase link --project-ref {{.SUPABASE_PROJECT_REF}}

  _supabase:db:push:
    desc: push database migrations to linked Supabase project
    cmds:
      - supabase db push

  _supabase:functions:deploy:
    desc: deploy edge functions to linked Supabase project
    cmds:
      - supabase functions deploy api

  _supabase:deploy:
    desc: deploy Supabase backend (migrations + functions)
    cmds:
      - task: _supabase:db:push
      - task: _supabase:functions:deploy

  _supabase:init:
    desc: initialize Supabase project (run once)
    cmds:
      - supabase init

  _supabase:start:
    desc: start local Supabase emulator
    cmds:
      - supabase start

  _supabase:stop:
    desc: stop local Supabase emulator
    cmds:
      - supabase stop

  _supabase:status:
    desc: show Supabase emulator status and connection info
    cmds:
      - supabase status

  _supabase:reset:
    desc: reset Supabase database and apply schema (local)
    cmds:
      - supabase db reset

  _supabase:reset-remote:
    desc: 'reset remote Supabase database (WARNING: deletes all data)'
    cmds:
      - supabase db reset --linked

  _supabase:studio:
    desc: open Supabase Studio UI in browser
    cmds:
      - supabase studio

  _stripe:local:
    desc: start Stripe CLI webhook listener for local billing tests
    cmds:
      - stripe listen --forward-to localhost:54321/functions/v1/api/billing/webhook
