#!/usr/bin/env python3
"""
Seed Stripe with subscription plans: Plus ($20), Pro ($50), Max ($200).

Creates products and prices, then updates ../api/supabase/.env with price IDs.

Usage:
  python scripts/seed-stripe.py
  python scripts/seed-stripe.py --dry-run    # show what would be created
"""
import argparse
import os
import sys
from pathlib import Path

try:
    import stripe
except ImportError:
    sys.exit('stripe package not installed. run: pip install stripe')


ENV_FILE = Path(__file__).resolve().parent.parent / 'api' / 'supabase' / '.env'

PLANS = [
    {
        'name': 'Plus Plan',
        'description': '$20 worth of credits/month, Share apps via App Clips, Vibecode Sandbox, Sandbox projects, App Store submission',
        'amount': 2000,  # $20.00
        'env_key': 'STRIPE_PRICE_PLUS',
    },
    {
        'name': 'Pro Plan',
        'description': '$55 worth of credits/month, Share apps via App Clips, Vibecode Sandbox, SSH to Cursor, Sandbox projects, App Store submission, Download source code',
        'amount': 5000,  # $50.00
        'env_key': 'STRIPE_PRICE_PRO',
    },
    {
        'name': 'Max Plan',
        'description': '$220 worth of credits/month, All Pro features, 24/7 Priority support, 10% bonus on credit purchases',
        'amount': 20000,  # $200.00
        'env_key': 'STRIPE_PRICE_MAX',
    },
]


def load_env_file(path: Path) -> None:
    """Load environment variables from a .env file."""
    if not path.exists():
        return
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        if '=' not in line:
            continue
        key, val = line.split('=', 1)
        key = key.strip()
        val = val.strip().strip('"').strip("'")
        os.environ.setdefault(key, val)


def get_stripe_key() -> str:
    """Get Stripe secret key from environment."""
    key = os.environ.get('STRIPE_SECRET_KEY')
    if not key:
        load_env_file(ENV_FILE)
        key = os.environ.get('STRIPE_SECRET_KEY')
    if not key:
        sys.exit('STRIPE_SECRET_KEY not found in environment or .env file')
    if not key.startswith('sk_test_'):
        sys.exit('refusing to run on non-test key (must start with sk_test_)')
    return key


def update_env_file(price_ids: dict[str, str]) -> None:
    """Update .env file with new price IDs."""
    if not ENV_FILE.exists():
        print(f'  {ENV_FILE} not found, skipping .env update')
        return
    # read existing content
    lines = ENV_FILE.read_text().splitlines()
    # remove old STRIPE_PRICE_ lines
    lines = [l for l in lines if not l.startswith('STRIPE_PRICE_')]
    # remove trailing empty lines
    while lines and not lines[-1].strip():
        lines.pop()
    # add new price IDs
    lines.append('')
    lines.append('# Stripe Price IDs (auto-generated by seed-stripe.py)')
    for env_key, price_id in price_ids.items():
        lines.append(f'{env_key}={price_id}')
    # write back
    ENV_FILE.write_text('\n'.join(lines) + '\n')
    print(f'  updated {ENV_FILE}')


def create_plans(dry_run: bool = False) -> dict[str, str]:
    """Create all subscription plans in Stripe."""
    price_ids = {}
    for plan in PLANS:
        print(f"creating {plan['name']}...")
        if dry_run:
            print(f"  would create product: {plan['name']}")
            print(f"  would create price: ${plan['amount'] / 100:.2f}/month")
            price_ids[plan['env_key']] = 'price_dry_run_xxx'
            continue
        # create product
        product = stripe.Product.create(
            name=plan['name'],
            description=plan['description'],
        )
        print(f"  created product: {product.id}")
        # create price
        price = stripe.Price.create(
            product=product.id,
            unit_amount=plan['amount'],
            currency='usd',
            recurring={'interval': 'month'},
        )
        print(f"  created price: {price.id}")
        price_ids[plan['env_key']] = price.id
    return price_ids


def main():
    parser = argparse.ArgumentParser(description='Seed Stripe with subscription plans')
    parser.add_argument('--dry-run', action='store_true', help='show what would be created')
    args = parser.parse_args()
    # init stripe
    stripe.api_key = get_stripe_key()
    print(f'using stripe key: {stripe.api_key[:12]}...')
    print()
    # create plans
    price_ids = create_plans(args.dry_run)
    print()
    # update .env
    if not args.dry_run:
        print('updating .env file...')
        update_env_file(price_ids)
    print()
    # print export commands
    print('export these environment variables:')
    print()
    for env_key, price_id in price_ids.items():
        print(f'  export {env_key}={price_id}')
    print()
    print('then restart supabase functions to pick up the new env vars')


if __name__ == '__main__':
    main()






